name: 'Create Branch'
description: 'Creates a branch'
author: 'Peter Grainger (peter@grainger)'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  branch:
    description: 'The branch to create'
    default: 'release-candidate'
  sha:
    description: 'The SHA1 value for the branch reference'
outputs:
  created:
    description: 'Boolean value representing whether or not a new branch was created.'
runs:
  using: 'node20'
  main: 'dist/index.js'
